/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_route_2eproto__INCLUDED
#define PROTOBUF_C_route_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Route Route;


/* --- enums --- */


/* --- messages --- */

struct  _Route
{
  ProtobufCMessage base;
  char *destination_ip;
  char *subnet_mask;
  char *nexthop_ip;
  protobuf_c_boolean has_metric;
  int32_t metric;
};
#define ROUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&route__descriptor) \
    , NULL, NULL, NULL, 0,0 }


/* Route methods */
void   route__init
                     (Route         *message);
size_t route__get_packed_size
                     (const Route   *message);
size_t route__pack
                     (const Route   *message,
                      uint8_t             *out);
size_t route__pack_to_buffer
                     (const Route   *message,
                      ProtobufCBuffer     *buffer);
Route *
       route__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   route__free_unpacked
                     (Route *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Route_Closure)
                 (const Route *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor route__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_route_2eproto__INCLUDED */
