/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "route.pb-c.h"
void   route__init
                     (Route         *message)
{
  static Route init_value = ROUTE__INIT;
  *message = init_value;
}
size_t route__get_packed_size
                     (const Route *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &route__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__pack
                     (const Route *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &route__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__pack_to_buffer
                     (const Route *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &route__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route *
       route__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route *)
     protobuf_c_message_unpack (&route__descriptor,
                                allocator, len, data);
}
void   route__free_unpacked
                     (Route *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &route__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor route__field_descriptors[4] =
{
  {
    "destination_ip",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Route, destination_ip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "subnet_mask",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Route, subnet_mask),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "nexthop_ip",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Route, nexthop_ip),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "metric",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Route, has_metric),
    PROTOBUF_C_OFFSETOF(Route, metric),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned route__field_indices_by_name[] = {
  0,   /* field[0] = destination_ip */
  3,   /* field[3] = metric */
  2,   /* field[2] = nexthop_ip */
  1,   /* field[1] = subnet_mask */
};
static const ProtobufCIntRange route__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor route__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Route",
  "Route",
  "Route",
  "",
  sizeof(Route),
  4,
  route__field_descriptors,
  route__field_indices_by_name,
  1,  route__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
